# frozen_string_literal: true

module USB
  LIBUSB_SUCCESS = 0
  LIBUSB_ERROR_IO = -1
  LIBUSB_ERROR_INVALID_PARAM = -2
  LIBUSB_ERROR_ACCESS = -3
  LIBUSB_ERROR_NO_DEVICE = -4
  LIBUSB_ERROR_NOT_FOUND = -5
  LIBUSB_ERROR_BUSY = -6
  LIBUSB_ERROR_TIMEOUT = -7
  LIBUSB_ERROR_OVERFLOW = -8
  LIBUSB_ERROR_PIPE = -9
  LIBUSB_ERROR_INTERRUPTED = -10
  LIBUSB_ERROR_NO_MEM = -11
  LIBUSB_ERROR_NOT_SUPPORTED = -12
  LIBUSB_ERROR_OTHER = -99

  TRANSFER_COMPLETED = 0
  TRANSFER_ERROR = 1
  TRANSFER_TIMED_OUT = 2
  TRANSFER_CANCELLED = 3
  TRANSFER_STALL = 4
  TRANSFER_NO_DEVICE = 5
  TRANSFER_OVERFLOW = 6

  TRANSFER_TYPE_CONTROL = 0
  TRANSFER_TYPE_ISOCHRONOUS = 1
  TRANSFER_TYPE_BULK = 2
  TRANSFER_TYPE_INTERRUPT = 3
  TRANSFER_TYPE_BULK_STREAM = 4

  TRANSFER_SHORT_NOT_OK = 1 << 0
  TRANSFER_FREE_BUFFER = 1 << 1
  TRANSFER_FREE_TRANSFER = 1 << 2
  TRANSFER_ADD_ZERO_PACKET = 1 << 3

  ENDPOINT_IN = 0x80
  ENDPOINT_OUT = 0x00

  REQUEST_TYPE_STANDARD = 0x00 << 5
  REQUEST_TYPE_CLASS = 0x01 << 5
  REQUEST_TYPE_VENDOR = 0x02 << 5
  REQUEST_TYPE_RESERVED = 0x03 << 5

  RECIPIENT_DEVICE = 0x00
  RECIPIENT_INTERFACE = 0x01
  RECIPIENT_ENDPOINT = 0x02
  RECIPIENT_OTHER = 0x03

  REQUEST_GET_STATUS = 0x00
  REQUEST_CLEAR_FEATURE = 0x01
  REQUEST_SET_FEATURE = 0x03
  REQUEST_SET_ADDRESS = 0x05
  REQUEST_GET_DESCRIPTOR = 0x06
  REQUEST_SET_DESCRIPTOR = 0x07
  REQUEST_GET_CONFIGURATION = 0x08
  REQUEST_SET_CONFIGURATION = 0x09
  REQUEST_GET_INTERFACE = 0x0A
  REQUEST_SET_INTERFACE = 0x0B
  REQUEST_SYNCH_FRAME = 0x0C
  REQUEST_SET_SEL = 0x30
  REQUEST_SET_ISOCH_DELAY = 0x31

  DT_DEVICE = 0x01
  DT_CONFIG = 0x02
  DT_STRING = 0x03
  DT_INTERFACE = 0x04
  DT_ENDPOINT = 0x05
  DT_BOS = 0x0F
  DT_DEVICE_CAPABILITY = 0x10
  DT_SS_ENDPOINT_COMPANION = 0x30
  DT_SUPERSPEED_HUB = 0x2A

  CLASS_PER_INTERFACE = 0x00
  CLASS_AUDIO = 0x01
  CLASS_COMM = 0x02
  CLASS_HID = 0x03
  CLASS_PHYSICAL = 0x05
  CLASS_IMAGE = 0x06
  CLASS_PRINTER = 0x07
  CLASS_MASS_STORAGE = 0x08
  CLASS_HUB = 0x09
  CLASS_DATA = 0x0A
  CLASS_SMART_CARD = 0x0B
  CLASS_CONTENT_SECURITY = 0x0D
  CLASS_VIDEO = 0x0E
  CLASS_PERSONAL_HEALTHCARE = 0x0F
  CLASS_DIAGNOSTIC_DEVICE = 0xDC
  CLASS_WIRELESS = 0xE0
  CLASS_MISCELLANEOUS = 0xEF
  CLASS_APPLICATION = 0xFE
  CLASS_VENDOR_SPEC = 0xFF

  SPEED_UNKNOWN = 0
  SPEED_LOW = 1
  SPEED_FULL = 2
  SPEED_HIGH = 3
  SPEED_SUPER = 4
  SPEED_SUPER_PLUS = 5

  LOG_LEVEL_NONE = 0
  LOG_LEVEL_ERROR = 1
  LOG_LEVEL_WARNING = 2
  LOG_LEVEL_INFO = 3
  LOG_LEVEL_DEBUG = 4

  HOTPLUG_EVENT_DEVICE_ARRIVED = 0x01
  HOTPLUG_EVENT_DEVICE_LEFT = 0x02

  HOTPLUG_ENUMERATE = 1 << 0
  HOTPLUG_MATCH_ANY = -1

  CAP_HAS_CAPABILITY = 0x0000
  CAP_HAS_HOTPLUG = 0x0001
  CAP_HAS_HID_ACCESS = 0x0100
  CAP_SUPPORTS_DETACH_KERNEL_DRIVER = 0x0101

  OPTION_LOG_LEVEL = 0
  OPTION_USE_USBDK = 1
  OPTION_NO_DEVICE_DISCOVERY = 2
  OPTION_LOG_CB = 3

  BT_WIRELESS_USB_DEVICE_CAPABILITY = 1
  BT_USB_2_0_EXTENSION = 2
  BT_SS_USB_DEVICE_CAPABILITY = 3
  BT_CONTAINER_ID = 4
  BT_PLATFORM_DESCRIPTOR = 5
end
